### ISSUE TITLE
Request about logger

### ISSUE THREAD

**Issue by riki-dexter** [Dymerz/SMA-SunnyBoy#1]
Hi, do you know how to interpret value received from getLogger?
I'd like to draw production chart but values received from getLogger have to be manipulated before drawing.
Do you know how?
Thank you

**Comment by Dymerz** [comment]
Hi, `getLogger()` return an array of dictionary values:
`[{'t': 1566701100, 'v': 9730397}, {'t': 1566701400, 'v': 9730397}]`
- 't' is the timestamp of the point.
- 'v' is the total power production.

Sadly you have to process yourself, these values are directly returned by the SMA web server, and it would take a lot of resources to calculate each point.

For myself, I call every 5 minutes the `getValue()`, process the data and store in a database.
I only use `getLogger()` for recovery purposes (eg: in case of power interruption).

Sorry for the late answer, I've just seen that notifications were disabled on this repo. 😞

**Comment by Dymerz** [comment]
Due to the innactivity I'm closing this issue.
