### ISSUE TITLE
Expand the documentation re: basic use

### ISSUE THREAD

**Issue by sfirke** [Dymerz/SMA-SunnyBoy#20]
I'm trying to use this package to pull solar production data but I could use more guidance on what arguments to supply to `WebConnect`.  What value do I put for `Right.USER` and how do I define that?  And what value do I supply for the IP address?  I posted this on StackOverflow too in case anyone would rather answer there: https://stackoverflow.com/questions/72018111/what-values-to-pass-for-arguments-to-webconnect-in-the-sma-sunnyboy-package

**Comment by sfirke** [comment]
Ah, is the IP address the one belonging to the SMA unit?  I thought this package connected to the SunnyBoy API, rather than directly querying the unit - maybe I misunderstood.

**Comment by Dymerz** [comment]
Yes, this package allows to fetch data directly from the SMA unit.
If you know your user credential you can access these data directly from you LAN network.

**Comment by sfirke** [comment]
Got it!  Good to know.  I'd wanted to query data via the API but getting set up with credentials looks to be difficult, so I may take a shot at this instead.  Thanks for the reply.
