### ISSUE TITLE
Request about getlogger #2 

### ISSUE THREAD

**Issue by k-sartor** [Dymerz/SMA-SunnyBoy#5]
Hi what is the format of start and end argument of getLogger() function?
Thank you

**Comment by Dymerz** [comment]
The `getLogger ` function is able to retrieve solar production in the specified timestamp range, meaning you have to pass the **timestamp** of the start and the end date.
```python
def get_logger(self, start: int, end: int):
```

I understand the documentation is not clear and so I'm working on a better documentation.

**Comment by k-sartor** [comment]
Thank you, i will test this soon

**Comment by k-sartor** [comment]
Ok, it's work... Thank you. The topic can be closed.
Notice due to precision (1 Wh), the extrapolation of this data to power during the time interval has a precision of 12 W (1 Wh = 3600 J during 300 seconds (5 minutes) )
